development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: ps3club.kh@gmail.com
  :password: ooops3club
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: ps3club.kh@gmail.com
  :password: ooops3club
  :enable_starttls_auto: true